login_homepage:
    path:     /
    defaults: { _controller: testBundle:login:user }
    
signup:
    path:     /signup
    defaults: {_controller: testBundle:login:signup}

logout:
    path:     /out
    defaults: { _controller: testBundle:logout:out }

post:
    path:     /post
    defaults: { _controller: testBundle:login:post}

profile:
    path:     /profile
    defaults: { _controller: testBundle:login:viewprofile}
    
postpage:
    path:    /posts/{postid}
    defaults: { _controller: testBundle:login:viewpost}
    
like:
    path:    /likes/{postid}
    defaults: { _controller: testBundle:login:like}
    
comment:
    path:    /comment/{postid}
    defaults: { _controller: testBundle:login:comment}