TestBundle\testBundle\Entity\Posts:
    type: entity
    table: posts
    indexes:
        userid:
            columns:
                - userid
    id:
        postid:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        postcontent:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
    manyToOne:
        userid:
            targetEntity: Users
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                userid:
                    referencedColumnName: userid
            orphanRemoval: false
    lifecycleCallbacks: {  }
